### PR TITLE
chore: docs draft

### LINKED ISSUE #8: Plugin documentation
@vanrez-nez Maybe I can start on a branch for this after we merge #2

### LINKED ISSUE #29: Plugin naming and attributes
https://craftcms.com/docs/5.x/extend/plugin-guide.html

Plugin name remains Component Library and handle + namespace remains `component-library`

* Change repo name to `craft-component-library`
* Change composer package name to `madebyraygun/craft-component-library`
* Add extra information for developer and documentation URL

### PR DESCRIPTION
**Pull request by vanrez-nez**
closes #8 

Notes:
- The vite setup could be expanded greatly but, since that's already being documented in the official plugin it may be enough by just providing a demo repo and link to official git-repo?

### CODE REVIEW

**Comment by daltonrooney** [comment]
Oh sorry, I have a docs branch that I’ve been working on locally, I’ll merge that into this one. I think it’s pretty complete, and you’re right, we can use the demo repository for the vite config as well as the Craft CMS context examples.

**Comment by vanrez-nez** [comment]
Ouch sorry, I should have asked! I think you mentioned that during one of our calls.

**Comment by daltonrooney** [comment]
@vanrez-nez Just wanted to let you know that I'll be merging my changes in today and that should be good to close this PR. I'm also going to address https://github.com/madebyraygun/component-library/issues/29 in this PR, and I think we'll be good to release!

**Comment by daltonrooney** [comment]
Closes #29

**Pull request merged**
